liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/../../public"
                cache_prefix: "uploads/cache"
    loaders:
        default:
            filesystem:
                  data_root: "%kernel.project_dir%/../../shared/public"
